services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      # - ./backend/data:/app/data # Removed to fix locking issues on macOS
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./protos:/app/protos
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: web-client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./protos:/app/protos
    environment:
      - BACKEND_INTERNAL_HOST=backend:50051
    depends_on:
      - backend
